# Generated by Django 6.0.2 on 2026-02-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
