# Generated by Django 6.0.2 on 2026-02-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0002_add_description_to_download"),
    ]

    operations = [
        migrations.AlterField(
            model_name="download",
            name="duration",
            field=models.FloatField(
                blank=True, help_text="Duration in seconds", null=True
            ),
        ),
    ]
