# Generated by Django 6.0.2 on 2026-02-27 02:51

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def deduplicate_existing_downloads(apps, schema_editor):
    """Merge duplicate (user, url) entries before adding unique constraint."""
    Download = apps.get_model("downloads", "Download")
    from django.db.models import Count

    # Find (user, url) pairs with duplicates
    dupes = (
        Download.objects.values("user", "url")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )

    for group in dupes:
        entries = Download.objects.filter(
            user_id=group["user"], url=group["url"]
        ).order_by("-created_at")

        # Keep the newest entry, merge counts
        keeper = entries.first()
        keeper.download_count = entries.count()
        keeper.last_downloaded_at = keeper.created_at
        keeper.save(update_fields=["download_count", "last_downloaded_at"])

        # Delete the rest
        entries.exclude(pk=keeper.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0003_alter_download_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="download",
            options={"ordering": ["-last_downloaded_at"]},
        ),
        migrations.RemoveIndex(
            model_name="download",
            name="downloads_d_user_id_4b2b13_idx",
        ),
        migrations.AddField(
            model_name="download",
            name="download_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="download",
            name="last_downloaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        # Deduplicate existing data before adding the unique constraint
        migrations.RunPython(
            deduplicate_existing_downloads,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="download",
            index=models.Index(
                fields=["user", "-last_downloaded_at"],
                name="downloads_d_user_id_6f808d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="download",
            constraint=models.UniqueConstraint(
                fields=("user", "url"), name="unique_user_url"
            ),
        ),
    ]
